meta:
  engine: 4.1.0

units:
  kx: cx
  ky: cy

  $default_width: cx
  $default_height: cy

  cpx: 1 + kx / 2
  cpy: 1 + ky / 2

  # 2 or 3 thumb keys per side.
  thumb_keys_per_side: 3

  # Negative values rotate each half inward (mirrored on the right).
  inward_rotation: -12

  total_matrix_splay: 6
  half_separation: 105

  board_padding_top: 10
  board_padding_horizontal: 10
  board_padding_bottom: 0

  xiao_length: 21
  xiao_width: 17.5
  xiao_left_clearance: 4

  power_switch_right_clearance: -4
  power_switch_width: 6.7
  power_switch_length: 2.6
  
  battery_width: 60
  battery_length: 20
  battery_thickness: 5.5
  battery_top_clearance: 2

points:
  mirror: 0
  zones:
    left_matrix:
      anchor:
        shift: [-half_separation, 0]
      rotate: inward_rotation
      key:
        padding: ky
        spread: kx
        tags: [key, left]
      columns:
        pinky:
          key:
            column_net: C0
          rows:
            bottom:
              row_net: R2
              mirror.row_net: R5
            home:
              row_net: R1
              mirror.row_net: R4
            top:
              row_net: R0
              mirror.row_net: R3
        ring:
          key:
            splay: -total_matrix_splay / 2
            spread: kx + 0.5
            stagger: ky - 2
            column_net: C1
          rows:
            bottom:
              row_net: R2
              mirror.row_net: R5
            home:
              row_net: R1
              mirror.row_net: R4
            top:
              row_net: R0
              mirror.row_net: R3
        middle:
          key:
            splay: -total_matrix_splay / 2
            spread: kx + 0.5
            stagger: 3
            column_net: C2
          rows:
            bottom:
              row_net: R2
              mirror.row_net: R5
            home:
              row_net: R1
              mirror.row_net: R4
            top:
              row_net: R0
              mirror.row_net: R3
        pointer:
          key:
            stagger: -6
            column_net: C3
          rows:
            bottom:
              row_net: R2
              mirror.row_net: R5
            home:
              row_net: R1
              mirror.row_net: R4
            top:
              row_net: R0
              mirror.row_net: R3
        inner:
          key:
            stagger: -2
            column_net: C4
          rows:
            bottom:
              row_net: R2
              mirror.row_net: R5
            home:
              row_net: R1
              mirror.row_net: R4
            top:
              row_net: R0
              mirror.row_net: R3

    left_thumbs:
      anchor:
        ref: left_matrix_pointer_bottom
        shift: [0, -ky]
      key:
        padding: ky
        spread: kx
        tags: [key, left, thumb]
      columns:
        tucky:
          key:
            column_net: C5
            row_net: R0
            mirror.row_net: R3
        middle:
          key:
            shift: [0, -2]
            column_net: C5
            row_net: R1
            mirror.row_net: R4
        reachy:
          key:
            shift: [0, -4]
            column_net: C5
            row_net: R2
            mirror.row_net: R5
            # Optional 3rd thumb key.
            skip: false
      rows:
        cluster:

    rect_top_left:
      mirror: {}
      anchor:
        shift: [-board_padding_horizontal, board_padding_top]
        aggregate:
          method: intersect
          parts:
            - ref: left_matrix_pinky_bottom
              shift: [-kx, 0]
              rotate: total_matrix_splay
            - ref: left_matrix_ring_top
              shift: [0, ky / 2]
              rotate: 90 + total_matrix_splay / 2 - inward_rotation / 2
      key:
        tags: [bounds]

    rect_top_right:
      anchor:
        ref: mirror_rect_top_left
      key:
        tags: [bounds]
        asym: source

    rect_bottom_left:
      mirror: {}
      anchor:
        aggregate:
          method: intersect
          parts:
            - ref: rect_top_left
            - ref: left_thumbs_reachy_cluster
              shift: [6ky, 0]
              rotate: 90 - inward_rotation
      key:
        tags: [bounds]

    rect_bottom_right:
      anchor:
        ref: mirror_rect_bottom_left
      key:
        tags: [bounds]
        asym: source

    mcu_xiao:
      key.tags: [mcu]
      anchor:
        ref: rect_top_left
        shift: [xiao_left_clearance + xiao_width / 2, -xiao_length / 2]

    power_switch:
      key:
        tags: [power_switch]
        asym: source
      anchor:
        ref: rect_top_right
        shift: [power_switch_right_clearance - power_switch_width / 2, -power_switch_length / 2]

    battery_pack:
      key:
        tags: [battery]
        asym: source
      anchor:
        - affect: x
        - ref: rect_top_left
          shift: [0, board_padding_horizontal - battery_length - battery_top_clearance]
          affect: y

outlines:
  _demo:
    - what: rectangle
      where: [key]
      size: [kx, ky]

  _xiao_debug:
    - what: rectangle
      where: mcu_xiao
      size: [xiao_width, xiao_length]

  _battery_debug:
    - what: rectangle
      where: battery_pack
      size: [battery_width, battery_length]

  _power_switch_debug:
    - what: rectangle
      where: power_switch
      size: [power_switch_width, power_switch_length]

  _outer_rect:
    - what: polygon
      joints: pointy
      fillet: 2
      points:
        - ref: rect_top_left
        - ref: rect_top_right
        - ref: rect_bottom_right
        - ref: rect_bottom_left

  board:
    - name: _outer_rect

  debug:
    - name: board
    - operation: stack
      name: _demo
    - operation: stack
      name: _xiao_debug
    - operation: stack
      name: _battery_debug
    - operation: stack
      name: _power_switch_debug

pcbs:
  limbatus:
    template: kicad8
    outlines:
      main:
        outline: board
    footprints:
      switches:
        what: ceoloide/switch_choc_v1_v2
        where: [key]
        params:
          choc_v2_support: false
          reversible: false
          hotswap: true
          include_corner_marks: true
          include_keycap: true
          include_centerhole_net: true
          keycap_height: ky
          keycap_width: kx

          # Matrix wiring scaffold.
          from: "{{column_net}}"
          to: "SW_{{name}}"

      diodes:
        what: ceoloide/diode_tht_sod123
        where: [key]
        adjust:
          shift: [0, -8.5]
        params:
          side: F
          from: "SW_{{name}}"
          to: "{{row_net}}"

      xiao_ble:
        what: ImStuBTW/xiao-ble
        where: mcu_xiao
        params:
          P0: C0
          P1: C1
          P2: C2
          P3: C3
          P4: C4
          P5: C5
          P6: R0
          P7: R1
          P8: R2
          P9: R3
          P10: R4
          NFC1: R5

      power_switch:
        what: ceoloide/power_switch_smd_side
        where: power_switch
        adjust:
          rotate: 90
        params:
          reversible: false
          from: Braw
          to: RAW
